CREATE TABLE IF NOT EXISTS seo_meta (
    id                       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    entity_type              VARCHAR(50) NOT NULL,
    entity_id                BIGINT UNSIGNED NOT NULL,
    meta_title               VARCHAR(255) NULL,
    meta_description         VARCHAR(500) NULL,
    canonical_url            VARCHAR(500) NULL,
    robots                   VARCHAR(100) NULL,
    og_title                 VARCHAR(255) NULL,
    og_description           VARCHAR(500) NULL,
    og_image_media_id        BIGINT UNSIGNED NULL,
    og_type                  VARCHAR(50) NULL,
    twitter_card              VARCHAR(50) NULL,
    twitter_title             VARCHAR(255) NULL,
    twitter_description       VARCHAR(500) NULL,
    twitter_image_media_id    BIGINT UNSIGNED NULL,
    ai_summary                VARCHAR(750) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_seo_meta_entity (entity_type, entity_id),
    KEY idx_seo_meta_og_image (og_image_media_id),
    KEY idx_seo_meta_twitter_image (twitter_image_media_id),
    CONSTRAINT fk_seo_meta_og_image FOREIGN KEY (og_image_media_id) REFERENCES media(id) ON DELETE SET NULL,
    CONSTRAINT fk_seo_meta_twitter_image FOREIGN KEY (twitter_image_media_id) REFERENCES media(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
